language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk11
before_install:
  - sudo apt-get update
  # workaround for missing ca certs in openjdk
  - sudo dpkg --purge --force-depends ca-certificates-java
  - sudo apt-get install ca-certificates-java
  - git config --global user.email "travis-ci@travis-ci.com"
  - git config --global user.name "Travis CI"
script: mvn compile test
jobs:
  include:
    - stage: deploy
      jdk: oraclejdk8
      deploy:
        provider: script
        script: bash ./.travis/deploy.sh
        on:
          branch: master
