debug: false
databases:
  # Local Database is always required. If not enabled, plugin will disable on startup.
  local:
    enabled: false
    host: 127.0.0.1
    port: 3306
    name: local_bans
    user: root
    password: ''
    maxConnections: 10
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerWarnings: bm_player_warnings
      playerReports: bm_player_reports
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records

  # External is only required if you want to sync with other servers, but still have separate bans, mutes etc.
  # This will enable /*all commands, e.g. /banall, /muteall
  external:
    enabled: false
    host: 127.0.0.1
    port: 3306
    name: external_bans
    user: root
    password: ''
    maxConnections: 10
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all

  # Only for converting a non-UUID v4 BanManager database
  convert:
    enabled: false
    host: 127.0.0.1
    port: 3306
    name: local_bans
    user: root
    password: ''
    maxConnections: 10
    tables:
      bansTable: bm_bans
      bansRecordTable: bm_ban_records
      ipBansTable: bm_ip_bans
      ipBansRecordTable: bm_ip_records
      kicksTable: bm_kicks
      mutesTable: bm_mutes
      mutesRecordTable: bm_mutes_records
      playerIpsTable: bm_player_ips
      warningsTable: bm_warnings

# Aliases will be found and blocked automatically, e.g. msg will block tell
mutedCommandBlacklist:
- msg

# Aliases will be found and blocked automatically, e.g. msg will block tell
softMutedCommandBlacklist:
- msg

# Displays a warning to those with bm.notify.duplicateips permission if joining players have the same ip as a banned player
duplicateIpCheck: true

# A list of IPs to exclude from the banned player duplicate check
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1

# Log /kick to the database?
logKicks: false

# Broadcasts events to those with bm.notify.X permissions, including command success
displayNotifications: true

# Broadcasts when new punishments are synced
broadcastOnSync: false

# Simply give the permission bm.timelimit.playerMutes.X or bm.timelimit.playerBans.X to apply the time limits
# replace X with the group defined here, can be anything you like.
timeLimits:
  playerMutes:
#    Moderator: 1h
  playerBans:
#    Moderator: 1d
  playerWarnings:
#    Moderator: 30d
  ipBans:
#    Moderator: 1d

# To prevent duplicate reports you can set a cooldown to limit the amount in seconds before a player can be reported again
# Set to 0 to disable
reportCooldown: 10

# To prevent duplicate warnings you can set a cooldown to limit the amount in seconds before a player can be warned again
# Set to 0 to disable
warningCooldown: 10

# Commands to execute when a player reaches a certain number of warnings
warningActions:
  enabled: false
  actions:
#    '10':
#     - cmd: ban [player] [reason]
# delays are in seconds
#       delay: 10
#     - cmd: mute [player] [reason]

# This allows running commands before and after a punishment
hooks:
  enabled: false
  # Can use ban, tempban, unban, mute, tempmute, unmute, warn, tempwarn, ipban, tempipban, unbanip, iprangeban,
  # tempiprangeban, unbaniprange, note
  events:
#   ban:
#     pre:
#     - cmd: kick [player] [reason]
# delays are in seconds
#       delay: 10
#     - cmd: banip [player] [reason]
#     post:
#     - cmd: broadcast [player] banned

# Set to false to disable update checks
checkForUpdates: true

# Set to false to disable offline name completion
offlineAutoComplete: true

# Automatically apply punishments to alts
# This is disabled by default as this could block siblings or those on shared networks
punishAlts: false

# Keep records for number of days, use 0 to never delete
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0

# Maximum amount of players allowed from a single ip, set to 0 to disable
maxOnlinePerIp: 0
